function getNamesMapObject() {
	return _namesMap = {
		Adam: 'Адам',
		Adel: 'Адель',
		Adelina: 'Аделина',
		Afanasy: 'Афанасий',
		Agafia: 'Агафья',
		Agafon: 'Агафон',
		Agneta: 'Агнета',
		Agnetha: 'Агнета',
		Aguei: 'Агей',
		Ahmed: 'Ахмед',
		Akim: 'Аким',
		Akoulina: 'Акулина',
		Alan: 'Алан',
		Albert: 'Альберт',
		Albina: 'Альбина',
		Alekcandr: 'Александр',
		Aleksander: 'Александр',
		Aleksandr: 'Александр',
		Aleksandra: 'Александра',
		Aleksei: 'Алексей',
		Aleksej: 'Алексей',
		Aleksey: 'Алексей',
		Alena: 'Алена',
		Alevtina: 'Алевтина',
		Alexander: 'Александр',
		Alexandr: 'Александр',
		Alexandra: 'Александра',
		Alexcandr: 'Александр',
		Alexei: 'Алексей',
		Alexey: 'Алексей',
		Alfiya: 'Альфия',
		Alina: 'Алина',
		Alisa: 'Алиса',
		Aliya: 'Алия',
		Alla: 'Алла',
		Almaz: 'Алмаз',
		Alsu: 'Алсу',
		Alyona: 'Алена',
		Amina: 'Амина',
		Amur: 'Амур',
		Anasstasia: 'Анастасия',
		Anastasia: 'Анастасия',
		Anastasiia: 'Анастасия',
		Anastasiya: 'Анастасия',
		Anastasya: 'Анастасия',
		Anatolii: 'Анатолий',
		Anatoliy: 'Анатолий',
		Anatoly: 'Анатолий',
		Andgelika: 'Анжелика',
		Andrei: 'Андрей',
		Andrej: 'Андрей',
		Andrey: 'Андрей',
		Anfisa: 'Анфиса',
		Angelica: 'Анжелика',
		Angelina: 'Ангелина',
		Anisy: 'Анисий',
		Anna: 'Анна',
		Anton: 'Антон',
		Antonina: 'Антонина',
		Antosha: 'Антоша',
		Anya: 'Аня',
		Anzhela: 'Анжела',
		Anzhelika: 'Анжелика',
		Ara: 'Ара',
		Arina: 'Арина',
		Arkadij: 'Аркадий',
		Arkadiy: 'Аркадий',
		Arkady: 'Аркадий',
		Arkasha: 'Аркаша',
		Arkhip: 'Архип',
		Arsen: 'Арсен',
		Arsenty: 'Арсентий',
		Artem: 'Артём',
		Arthur: 'Артур',
		Artur: 'Артур',
		Artyom: 'Артем',
		Asel: 'Асель',
		Avgusta: 'Августа',
		Ayshat: 'Айшат',
		Azamat: 'Азамат',
		Bekman: 'Бекман',
		Bella: 'Бэлла',
		Bogdan: 'Богдан',
		Boris: 'Борис',
		Borya: 'Боря',
		Damir: 'Дамир',
		Dania: 'Даня',
		Daniel: 'Даниэль',
		Daniil: 'Даниил',
		Danil: 'Данил',
		Danila: 'Данила',
		Daria: 'Дарья',
		Darina: 'Дарина',
		Dariya: 'Дарья',
		Darya: 'Дарья',
		David: 'Давид',
		Demid: 'Демид',
		Denis: 'Денис',
		Diana: 'Диана',
		Dilara: 'Диляра',
		Diliara: 'Диляра',
		Dilyara: 'Диляра',
		Dina: 'Дина',
		Dinara: 'Динара',
		Dmitrii: 'Дмитрий',
		Dmitrij: 'Дмитрий',
		Dmitriy: 'Дмитрий',
		Dmitry: 'Дмитрий',
		Edgar: 'Эдгар',
		Edik: 'Эдик',
		Eduard: 'Эдуард',
		Edward: 'Эдуард',
		Efim: 'Ефим',
		Efrem: 'Ефрем',
		Efrosinia: 'Ефросинья',
		Egor: 'Егор',
		Ekaterina: 'Екатерина',
		Elena: 'Елена',
		Elina: 'Элина',
		Elisaveta: 'Елизавета',
		Elizaveta: 'Елизавета',
		Ella: 'Элла',
		Elmira: 'Эльмира',
		Elvira: 'Эльвира',
		Emelian: 'Емельян',
		Emil: 'Эмиль',
		Emilia: 'Эмилия',
		Emiliia: 'Эмилия',
		Emiliya: 'Эмилия',
		Emina: 'Эмина',
		Ermolay: 'Ермолай',
		Ernest: 'Эрнест',
		Eugeniy: 'Евгений',
		Eva: 'Ева',
		Evdokia: 'Евдокия',
		Evdokim: 'Евдоким',
		Evelina: 'Эвелина',
		Evgeni: 'Евгений',
		Evgenia: 'Евгения',
		Evgenii: 'Евгений',
		Evgeniia: 'Евгения',
		Evgenij: 'Евгений',
		Evgeniy: 'Евгений',
		Evgeniya: 'Евгения',
		Evgeny: 'Евгений',
		Evgenyi: 'Евгений',
		Fadey: 'Фадей',
		Fedor: 'Фёдор',
		Fedosia: 'Федосья',
		Fedot: 'Федот',
		Fedya: 'Федя',
		Fekla: 'Фекла',
		Filipp: 'Филипп',
		Foma: 'Фома',
		Frol: 'Фрол',
		Fyodor: 'Фёдор',
		Galina: 'Галина',
		Galiya: 'Галия',
		Galya: 'Галя',
		Gavriil: 'Гавриил',
		Genadij: 'Геннадий',
		Gennadii: 'Геннадий',
		Gennadiy: 'Геннадий',
		Gennady: 'Геннадий',
		Georgii: 'Георгий',
		Georgij: 'Георгий',
		Georgiy: 'Георгий',
		Georgy: 'Георгий',
		Gerasim: 'Герасим',
		German: 'Герман',
		Gleb: 'Глеб',
		Gosha: 'Гоша',
		Grigorii: 'Григорий',
		Grigoriy: 'Григорий',
		Grigory: 'Григорий',
		Grygory: 'Григорий',
		Gulnara: 'Гульнара',
		Gulnur: 'Гульнур',
		Guzel: 'Гузель',
		Halid: 'Халид',
		Iakov: 'Яков',
		Iana: 'Яна',
		Ignat: 'Игнат',
		Igor: 'Игорь',
		Ildar: 'Ильдар',
		Ilia: 'Илья',
		Iliya: 'Илья',
		Ilnur: 'Ильнур',
		Ilona: 'Илона',
		Ilshat: 'Ильшат',
		Ilya: 'Илья',
		Ilyusha: 'Илюша',
		Inna: 'Инна',
		Innokentiy: 'Иннокентий',
		Innokenty: 'Иннокентий',
		Iosif: 'Иосиф',
		Ira: 'Ира',
		Irina: 'Ирина',
		Iskander: 'Искандер',
		Islam: 'Ислам',
		Iuliia: 'Юлия',
		Iuliya: 'Юлия',
		Iurii: 'Юрий',
		Ivan: 'Иван',
		Julia: 'Юлия',
		Juliya: 'Юлия',
		Kamil: 'Камиль',
		Kamilla: 'Камилла',
		Karina: 'Карина',
		Karolina: 'Каролина',
		Katerina: 'Катерина',
		Katya: 'Катя',
		Kesha: 'Кеша',
		Khalid: 'Халид',
		Khariton: 'Харитон',
		Khristina: 'Христина',
		Kira: 'Кира',
		Kirill: 'Кирилл',
		Klementy: 'Клементий',
		Kolya: 'Коля',
		Konstantin: 'Константин',
		Kostya: 'Костя',
		Kouzma: 'Кузьма',
		Kristina: 'Кристина',
		Ksenia: 'Ксения',
		Kseniia: 'Ксения',
		Kseniya: 'Ксения',
		Ksenya: 'Ксения',
		Lara: 'Лара',
		Larion: 'Ларион',
		Larisa: 'Лариса',
		Lavrenty: 'Лаврентий',
		Lena: 'Лена',
		Leonid: 'Леонид',
		Leonty: 'Леонтий',
		Lera: 'Лера',
		Lesya: 'Леся',
		Lev: 'Лев',
		Liana: 'Лиана',
		Lianna: 'Лианна',
		Lidia: 'Лидия',
		Lidiya: 'Лидия',
		Lilia: 'Лилия',
		Liliia: 'Лилия',
		Liliya: 'Лилия',
		Lilya: 'Лилия',
		Lina: 'Лина',
		Liubov: 'Любовь',
		Liudmila: 'Людмила',
		Louka: 'Лука',
		Lubov: 'Любовь',
		Ludmila: 'Людмила',
		Luisa: 'Луиза',
		Lybov: 'Любовь',
		Lydia: 'Лидия',
		Lyova: 'Лёва',
		Lyuba: 'Люба',
		Lyubov: 'Любовь',
		Lyudmila: 'Людмила',
		Madina: 'Мадина',
		Makar: 'Макар',
		Maksim: 'Максим',
		Marat: 'Марат',
		Margarita: 'Маргарита',
		Maria: 'Мария',
		Marianna: 'Марианна',
		Mariia: 'Мария',
		Marina: 'Марина',
		Mariya: 'Мария',
		Mark: 'Марк',
		Marsel: 'Марсель',
		Maryna: 'Марина',
		Masha: 'Маша',
		Matrena: 'Матрена',
		Matvey: 'Матвей',
		Maxim: 'Максим',
		Michail: 'Михаил',
		Mihail: 'Михаил',
		Mihajl: 'Михаил',
		Mikhail: 'Михаил',
		Mila: 'Мила',
		Milena: 'Милена',
		Misha: 'Миша',
		Mitrofan: 'Митрофан',
		Nadegda: 'Надежда',
		Nadezda: 'Надежда',
		Nadezhda: 'Надежда',
		Nadya: 'Надя',
		Naida: 'Наида',
		Nargiza: 'Наргиза',
		Nastya: 'Настя',
		Natalia: 'Наталья',
		Nataliia: 'Наталья',
		Nataliya: 'Наталья',
		Natalya: 'Наталья',
		Natalyja: 'Наталья',
		Natasha: 'Наташа',
		Nelli: 'Нэлли',
		Nelly: 'Нэлли',
		Nikanor: 'Никанор',
		Nikifor: 'Никифор',
		Nikita: 'Никита',
		Nikolai: 'Николай',
		Nikolaj: 'Николай',
		Nikolay: 'Николай',
		Nina: 'Нина',
		Oksana: 'Оксана',
		Oleg: 'Олег',
		Olesia: 'Олеся',
		Olesiya: 'Олеся',
		Olesya: 'Олеся',
		Olga: 'Ольга',
		Olya: 'Оля',
		Pasha: 'Паша',
		Pavel: 'Павел',
		Petr: 'Пётр',
		Petya: 'Петя',
		Philipp: 'Филипп',
		Piotr: 'Пётр',
		Polina: 'Полина',
		Polya: 'Поля',
		Pyotr: 'Пётр',
		Rail: 'Раиль',
		Raisa: 'Раиса',
		Ramil: 'Рамиль',
		Rashid: 'Рашид',
		Rasul: 'Расул',
		Ravil: 'Равиль',
		Raya: 'Рая',
		Regina: 'Регина',
		Rifat: 'Рифат',
		Rinat: 'Ринат',
		Rodion: 'Родион',
		Roma: 'Рома',
		Roman: 'Роман',
		Rostislav: 'Ростислав',
		Ruslan: 'Руслан',
		Rustam: 'Рустам',
		Rustem: 'Рустем',
		Sabina: 'Сабина',
		Sasha: 'Саша',
		Saveliy: 'Савелий',
		Semen: 'Семен',
		Semyon: 'Семен',
		Senya: 'Сеня',
		Serafima: 'Серафима',
		Sergei: 'Сергей',
		Sergej: 'Сергей',
		Sergey: 'Сергей',
		Seryozha: 'Серёжа',
		Shamil: 'Шамиль',
		Slava: 'Слава',
		Sofia: 'София',
		Sofiia: 'София',
		Sofiya: 'София',
		Sofya: 'София',
		Stanislav: 'Станислав',
		Stella: 'Стелла',
		Stepan: 'Степан',
		Styopa: 'Стёпа',
		Sveta: 'Света',
		Svetlana: 'Светлана',
		Svyatoslav: 'Святослав',
		Syoma: 'Сёма',
		Taisiya: 'Таисия',
		Tamara: 'Тамара',
		Tanya: 'Таня',
		Tatiana: 'Татьяна',
		Tatiyana: 'Татьяна',
		Tatiyna: 'Татьяна',
		Tatyana: 'Татьяна',
		Tatyiana: 'Татьяна',
		Tatyjana: 'Татьяна',
		Taya: 'Тая',
		Tima: 'Тима',
		Timofei: 'Тимофей',
		Timofey: 'Тимофей',
		Timur: 'Тимур',
		Trifon: 'Трифон',
		Trofim: 'Трофим',
		Tyoma: 'Тёма',
		Uliana: 'Ульяна',
		Uliya: 'Юлия',
		Ulyana: 'Ульяна',
		Vacheslav: 'Вячеслав',
		Vadim: 'Вадим',
		Vagan: 'Ваган',
		Valentin: 'Валентин',
		Valentina: 'Валентина',
		Valera: 'Валера',
		Valeria: 'Валерия',
		Valerii: 'Валерий',
		Valeriia: 'Валерия',
		Valeriy: 'Валерий',
		Valeriya: 'Валерия',
		Valery: 'Валерий',
		Valerya: 'Валерия',
		Valya: 'Валя',
		Varvara: 'Варвара',
		Varya: 'Варя',
		Vasilii: 'Василий',
		Vasilisa: 'Василиса',
		Vasiliy: 'Василий',
		Vasily: 'Василий',
		Vazgen: 'Вазген',
		Venera: 'Венера',
		Veniamin: 'Вениамин',
		Vera: 'Вера',
		Veronica: 'Вероника',
		Veronika: 'Вероника',
		Viacheslav: 'Вячеслав',
		Viatcheslav: 'Вячеслав',
		Victor: 'Виктор',
		Victoria: 'Виктория',
		Victoriya: 'Виктория',
		Viktor: 'Виктор',
		Viktoria: 'Виктория',
		Viktoriia: 'Виктория',
		Viktoriya: 'Виктория',
		Violetta: 'Виолетта',
		Vitalii: 'Виталий',
		Vitalij: 'Виталий',
		Vitaliy: 'Виталий',
		Vitaly: 'Виталий',
		Vitalyi: 'Виталий',
		Vlada: 'Влада',
		Vladimir: 'Владимир',
		Vladislav: 'Владислав',
		Vladlen: 'Владлен',
		Vlas: 'Влас',
		Volodya: 'Володя',
		Vova: 'Вова',
		Vsevolod: 'Всеволод',
		Vyacheslav: 'Вячеслав',
		Xenia: 'Ксения',
		Yakov: 'Яков',
		Yan: 'Ян',
		Yana: 'Яна',
		Yarik: 'Ярик',
		Yaroslav: 'Ярослав',
		Yaroslava: 'Ярослава',
		Yekaterina: 'Екатерина',
		Yelena: 'Елена',
		Yevgenia: 'Евгения',
		Yevgeniy: 'Евгений',
		Yevgeny: 'Евгений',
		Yulia: 'Юлия',
		Yuliya: 'Юлия',
		Yulya: 'Юлия',
		Yura: 'Юра',
		Yuri: 'Юрий',
		Yurii: 'Юрий',
		Yurij: 'Юрий',
		Yuriy: 'Юрий',
		Yury: 'Юрий',
		Yuryi: 'Юрий',
		Zakhar: 'Захар',
		Zalina: 'Залина',
		Zarema: 'Зарема',
		Zareta: 'Зарета',
		Zarina: 'Зарина',
		Zhanna: 'Жанна',
		Zhenya: 'Женя',
		Zinaida: 'Зинаида',
		Zinovy: 'Зиновий',
		Zlata: 'Злата',
		Zoya: 'Зоя'
	  }
}

function getMonthsArray() {
	return _monthsArray = ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"]
}

function getEducationPlanStateName() {
	return _educationPlanStateName = {
        0: "Назначен",
        1: "В процессе",
        2: "Завершён",
        3: "Не пройден",
        4: "Пройден",
		5: "Просмотрен",
        6: "Отменён"
    };
}

function getPositionNamesMapObject() {
	return _positionNamesMap = {
		"FOH TM": "Член команды",
		"MOH TM": "Член команды",
		"BOH TM": "Член команды",
		"Team Member": "Член команды",
		"Team Trainer": "Тренер",
		"Shift Supervisor": "Менеджер смены",
		"Assistant Manager": "Заместитель директора ресторана",
		"RGM": "Директор ресторана",
		"RGM Trainee": "Директор ресторана (стажер)",
		"Area Coach": "Территориальный управляющий",
		"Region Coach": "Управляющий операционной деятельностью региона",
		"Market Coach": "Управляющий операционной деятельностью региона",
		"Market Manager": "Управляющий операционной деятельностью региона",
		"Key Operator": "Операционный директор",
		"Other": "Сотрудник центра поддержки ресторанов",
		"ROCC": "Сотрудник центра поддержки ресторанов"
	};
}

function getPositionParentNamesMapObject() {
	return _positionParentNamesMap = {
		"RSC (Restaurants Support Center)": "Центр поддержки ресторанов",
		"FZ_RSC (Restaurants Support Center)": "Центр поддержки ресторанов",
		"Без департамента": "Центр поддержки ресторанов"
	};
}

/**
 * 
 * @param {string} departmentCode - идентификатор департамента
 * @param {string} additionalText - дополнительный текст
 * @returns {string} описание роли
 */
function getPositionNameDescription(departmentCode, additionalText) {
	if (departmentCode = 'HR') {
		return _positionNameDescription = "любой текст про HR" + additionalText
	}
	if (departmentCode = 'IT') {
		return _positionNameDescription = additionalText + "любой текст про ИТ"
	}
}